name: real_image

image_shape: [3, 240, 320]
dataset_path: data/screwdriver/

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    camera_0:
      shape: ${task.image_shape}
      type: rgb
    robot_eef_pose:
      shape: [6]
    robot_eef_pose_vel:
      shape: [6]
      # type default: low_dim
    robot_joint:
      shape: [6]
  action: 
    shape: [6]

env_runner:
  _target_: diffusion_policy.env_runner.real_screwdriver_image_runner.RealScrewdriverImageRunner

dataset:
  _target_: diffusion_policy.dataset.real_screwdriver_dataset.RealScrewDriverDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  delta_action: False

